name: "Build and push images"

on:
  push:
    branches:
      - Hugging-Face          # 这里的 main 是你想要监听的分支名
         # 也可以使用通配符监听所有 release/ 开头的分支
  workflow_dispatch:  # 保留手动触发按钮

jobs:
  Building:
    runs-on: ubuntu-latest
    name: "Build Argo-X images"
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKERHUB_REPOSITORY: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.0.0
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.10.0

      - name: Login to DockerHub
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Push images to Docker hub
        uses: docker/build-push-action@v4.1.1
        with:
          push: true
          platforms: linux/amd64
          tags: ${{ env.DOCKERHUB_REPOSITORY }}
